# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Brief !
tagline:          'Blog de Ange Tato'
description:      "Bienvenue sur mon blog. Je partage avec vous des petites <b>recettes</b> brèves qui pourront être utiles à plus d'un dans le domaine de l'intelligence artificielle."
url:              http://hyde.getpoole.com
baseurl:          /angetato.github.io


author:
  name:           'Ange Tato'
  url:            angetato.com

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/angetato/

paginate: 5
paginate_path: "page:num"
gems: ["jemoji"]
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb